#
# This config-file is only needed for development. Instead of changing the url
# everytime you work locally on the project, you start both config-files, overwriting
# the first one with the development variables needed.
#
# gradle serve local

url: 'http://localhost:4000'

# Disable when not in production
google_analytics_tracking_id: false
disqus_shortname: false

liquid:
  # :lax acts like liquid 2.5 and silently ignores malformed tags in most cases.
  # :warn is the default and will give deprecation warnings when invalid syntax is used.
  # :strict will enforce correct syntax.
  error_mode: strict